In [126]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt 
import seaborn as sns

In [144]:
%%sql

SELECT 
    ad.teamname,
    ad.playername, 
    ad.champion,
    COUNT(ad.champion) AS champion_count,
    ROUND(AVG(ad.cspm),2) AS CSPM,
    SUM(ad.firstblood) AS FB,
    ROUND(SUM(ad.firstblood) / COUNT(ad.game)*100,1) AS FB_perce,
    ROUND(avg(ad.dpm),1) AS avg_champ_damage,
    ROUND(avg(ad.damageshare)*100,1) AS avg_champ_damageshare,
    ROUND(SUM(CASE WHEN ad.result = 1 THEN 1 ELSE 0 END) / COUNT(ad.result) *100, 2) AS win_rate_per,
    AVG(ad.gamelength) AS avg_game_length,
    STDDEV(ad.gamelength) AS std_game_length,
    ROUND(IF(SUM(ad.deaths + ad.assists) = 0, NULL, SUM(ad.kills + ad.assists) / SUM(ad.deaths)), 2) AS KDA,
    ROUND(SUM(IFNULL(ad.towers, 0)) / COUNT(ad.game), 1) AS total_towers_per_game,
    ROUND(SUM(IFNULL(ad.dragons, 0)) / COUNT(ad.game), 1) AS total_dragons_per_game
FROM 
    Worlds_2024.all_data_2024 ad
WHERE 
    ad.patch = '14.18' 
    AND ad.league LIKE '%WLD%'
    AND (ad.teamname LIKE '%Bili%' OR ad.teamname LIKE '%T1%')
GROUP BY 
    ad.playername, 
    ad.champion,
    ad.firsttower,
    ad.teamname,
    ad.towers
ORDER BY 
    ad.playername DESC;

,teamname,playername,champion,champion_count,CSPM,FB,FB_perce,avg_champ_damage,avg_champ_damageshare,win_rate_per,avg_game_length,std_game_length,KDA,total_towers_per_game,total_dragons_per_game
0,T1,Zeus,Camille,1,8.26,0,0.0,415.5,21.0,100.00,1917.0000,0.000000,NaN,0.0,0.0
1,T1,Zeus,Gnar,2,8.13,0,0.0,575.8,24.2,100.00,2148.5000,99.500000,7.00,0.0,0.0
2,T1,Zeus,Gragas,3,7.51,0,0.0,436.3,18.3,100.00,1798.0000,88.615273,16.50,0.0,0.0
3,T1,Zeus,Jax,3,8.22,1,33.3,455.5,19.7,66.67,2116.0000,283.030034,3.11,0.0,0.0
4,T1,Zeus,Maokai,1,7.98,0,0.0,291.3,24.6,0.00,1662.0000,0.000000,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Bilibili Gaming,NaN,NaN,0,33.07,2,66.7,3252.3,NaN,100.00,2041.3333,273.939572,4.87,10.0,3.0
86,T1,NaN,NaN,0,31.93,1,100.0,1745.2,NaN,0.00,1834.0000,0.000000,2.64,2.0,2.0
87,T1,NaN,NaN,0,34.56,2,66.7,2516.1,NaN,100.00,1916.0000,161.965017,6.13,8.0,3.7
88,T1,NaN,NaN,0,33.80,1,50.0,2209.0,NaN,100.00,2076.5000,171.500000,11.90,9.0,2.5
89,T1,NaN,NaN,0,34.18,1,100.0,1975.6,NaN,100.00,1917.0000,0.000000,11.60,11.0,4.0

In [133]:
%%sql
SELECT
    *
FROM 
    Worlds_2024.Worlds_2024_Players p
INNER JOIN 
    
    Worlds_2024.Worlds_2024_Teams t      
ON 
    p.Team = t.Team

AND (p.Team LIKE '%Bili%' OR p.Team LIKE '%T1%')
;

,Player,Team,Pos,GP,W%,CTR%,K,D,A,KDA,...,FD%,DRG%,ELD%,FBN%,BN%,LNE%,JNG%,WPM.1,CWPM.1,WCPM.1
0,Bin,Bilibili Gaming,Top,15,73%,40%,60,33,80,4.2,...,73%,50%,NaN,47%,57%,50.6%,50.0%,3.88,1.44,1.89
1,Elk,Bilibili Gaming,ADC,15,73%,60%,71,40,107,4.5,...,73%,50%,NaN,47%,57%,50.6%,50.0%,3.88,1.44,1.89
2,Faker,T1,Middle,12,83%,58%,47,25,76,4.9,...,42%,60%,100%,67%,79%,50.9%,52.5%,4.02,1.35,1.65
3,Gumayusi,T1,ADC,12,83%,33%,56,14,74,9.3,...,42%,60%,100%,67%,79%,50.9%,52.5%,4.02,1.35,1.65
4,Keria,T1,Support,12,83%,50%,6,22,137,6.5,...,42%,60%,100%,67%,79%,50.9%,52.5%,4.02,1.35,1.65
5,knight,Bilibili Gaming,Middle,15,73%,53%,82,31,105,6.0,...,73%,50%,NaN,47%,57%,50.6%,50.0%,3.88,1.44,1.89
6,ON,Bilibili Gaming,Support,15,73%,47%,7,62,157,2.6,...,73%,50%,NaN,47%,57%,50.6%,50.0%,3.88,1.44,1.89
7,Oner,T1,Jungle,12,83%,67%,33,21,103,6.5,...,42%,60%,100%,67%,79%,50.9%,52.5%,4.02,1.35,1.65
8,Wei,Bilibili Gaming,Jungle,3,33%,67%,3,12,34,3.1,...,73%,50%,NaN,47%,57%,50.6%,50.0%,3.88,1.44,1.89
9,Xun,Bilibili Gaming,Jungle,12,83%,50%,28,27,122,5.6,...,73%,50%,NaN,47%,57%,50.6%,50.0%,3.88,1.44,1.89
10,Zeus,T1,Top,12,83%,58%,38,19,81,6.3,...,42%,60%,100%,67%,79%,50.9%,52.5%,4.02,1.35,1.65